---
restylers:
  - stylish-haskell
  - brittany
  - prettier:
      # Explicitly set parser so it works on .julius
      arguments:
        - --parser
        - babylon # named babel after v1.16.0
      include:
        - "**/*.js"
        - "**/*.julius"
  - hlint:
      include:
        - "**/*.hs"

        # apply-refact cannot handle TypeApplications
        - "!src/Restyled/Handlers/PrivacyPolicy.hs"
        - "!src/Restyled/Handlers/Webhooks.hs"
        - "!src/Restyled/StreamJobLogLines.hs"

        # apply-refact cannot handle something here
        - "!src/Restyled/Env.hs"

        # apply-refact cannot handle forall
        - "!test/Restyled/Test/Yesod.hs"
