---
restylers:
  - stylish-haskell
  - brittany
  - prettier:
      # Explicitly set parser so it works on .julius
      arguments:
        - --parser
        - babylon # named babel after v1.16.0
      include:
        - "**/*.js"
        - "**/*.julius"
  - hlint:
      include:
        - "**/*.hs"
