restylers_version: dev
restylers:
  - fourmolu
  - hlint:
      include:
        - "**/*.hs"
        - "!src/Restyled/Settings.hs" # CPP
        - "!src/Restyled/Handlers/Revision.hs" # CPP
  - stylish-haskell:
      enabled: false
  - prettier:
      # Explicitly set parser so it works on .julius
      arguments:
        - --parser
        - babel
      include:
        - "**/*.js"
        - "**/*.julius"
  - shellharden:
      enabled: false
  - whitespace:
      include:
        - "**/*"
        - "!**/*.hamlet"
  - "*"
