remote_files:
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/config/brittany/config.yaml
    path: brittany.yaml
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
    path: .hlint.yaml
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/stylish-haskell.yaml
    path: .stylish-haskell.yaml

restylers_version: dev

restylers:
  - hlint
  - stylish-haskell
  - brittany
  - prettier:
      # Explicitly set parser so it works on .julius
      arguments:
        - --parser
        - babylon # named babel after v1.16.0
      include:
        - "**/*.js"
        - "**/*.julius"
  - shellharden:
      enabled: false
  - "*"
