---
restylers:
  - stylish-haskell
  - brittany
  - prettier:
      # Explicitly set parser so it works on .julius
      arguments:
        - --parser
        - babylon # named babel after v1.16.0
      include:
        - "**/*.js"
        - "**/*.julius"
  - hlint:
      include:
        - "**/*.hs"

        # apply-refact cannot handle TypeApplications
        - "!src/Handler/PrivacyPolicy.hs"
        - "!src/Handler/Webhooks.hs"
        - "!src/StreamJobLogLines.hs"

        # apply-refact cannot handle something here
        - "!src/Settings/Env.hs"
