- package:
  - name: jwt
- package:
  - name: yesod-auth-oauth2
- package:
  - name: restyled
  - section:
    - name: exe:restyled.io
    - message:
      - name: Module not compiled
      - module: DevelMain
