---
name: restyled
version: 0.1.1.0
license: MIT

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

  # Forcing addition of these in-module because of broken tooling
  # - LambdaCase

ghc-options: -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints

dependencies:
  - base

library:
  dependencies:
    - aeson
    - aeson-casing
    - ansi-terminal
    - blaze-html
    - blaze-markup
    - bytestring
    - cassava
    - composition-extra
    - conduit
    - conduit-extra
    - containers
    - data-default
    - envparse
    - errors
    - esqueleto
    - extra
    - fast-logger
    - file-embed
    - filepath
    - formatting
    - github
    - gitrev
    - hedis
    - hjsmin
    - http-conduit
    - http-types
    - hoauth2
    - iso8601-time
    - jwt
    - lens
    - lens-aeson
    - load-env
    - megaparsec
    - monad-logger
    - mtl
    - optparse-applicative
    - path-pieces
    - persistent
    - persistent-postgresql
    - persistent-qq
    - persistent-template
    - rio
    - rio-orphans
    - safe-exceptions
    - semigroups
    - shakespeare
    - tagged
    - template-haskell
    - text
    - time
    - transformers
    - unordered-containers
    - uri-encode
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - websockets
    - yesod
    - yesod-auth
    - yesod-auth-oauth2
    - yesod-core
    - yesod-form
    - yesod-paginator >= 1.1.0.2
    - yesod-persistent
    - yesod-static
    - yesod-websockets
  source-dirs: src

executables:
  restyled.io:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - load-env
      - restyled

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - restyled
      - QuickCheck
      - bytestring
      - filepath
      - github
      - hedis
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - http-types
      - lens
      - lens-aeson
      - load-env
      - megaparsec
      - monad-logger
      - persistent
      - rio
      - shakespeare
      - text
      - time
      - wai-extra
      - yesod-auth
      - yesod-core
      - yesod-test
