name:    restyled
version: "0.0.0"

# Dependencies shared in *all* targets
dependencies:
  - base

library:
  dependencies:
  - aeson
  - bytestring
  - case-insensitive
  - classy-prelude
  - classy-prelude-yesod
  - conduit
  - containers
  - envparse
  - fast-logger
  - file-embed
  - gitrev
  - hjsmin
  - HTTP
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - jwt
  - load-env
  - monad-control
  - monad-logger
  - network-uri
  - pandoc
  - persistent
  - persistent-postgresql
  - persistent-template
  - process
  - safe
  - shakespeare
  - skylighting
  - template-haskell
  - text
  - time
  - unordered-containers
  - vector
  - wai
  - wai-extra
  - wai-logger
  - warp
  - yesod
  - yesod-core
  - yesod-form
  - yesod-static
  source-dirs: src
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  restyled.io:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - restyled

  restyler:
    main: main.hs
    source-dirs: restyler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - restyled
    - classy-prelude
    - directory
    - filepath
    - optparse-applicative
    - process
    - shakespeare
    - temporary
    - text
    - yesod-core # PathPiece(..)

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - restyled
    - bytestring
    - classy-prelude
    - hspec
    - hspec-expectations-lifted
    - load-env
    - persistent
    - shakespeare
    - yesod-core
    - yesod-test

flags:
  library-only:
    description: Unused, but yesod-devel passes it.
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
