name: restyled
version: 0.1.1.0
license: MIT

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

  # Needed here just so HLint doesn't strip it
  - ViewPatterns

ghc-options: -Weverything
  -Wno-unsafe
  -Wno-missing-import-lists

cpp-options:
  -DDEVELOPMENT=0
  -DDOCKERIZED=0

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - ansi-terminal
    - blaze-html
    - blaze-markup
    - bytestring
    - cassava
    - composition-extra
    - conduit
    - conduit-extra
    - containers
    - data-default
    - envparse
    - errors
    - esqueleto
    - extra
    - fast-logger
    - file-embed
    - filepath
    - formatting
    - github
    - gitrev
    - hedis
    - hjsmin
    - http-conduit
    - http-types
    - hoauth2
    - iso8601-time
    - jwt
    - lens
    - lens-aeson
    - load-env
    - megaparsec
    - monad-logger
    - mtl
    - optparse-applicative
    - path-pieces
    - persistent
    - persistent-postgresql
    - persistent-qq
    - persistent-template
    - rio
    - rio-orphans
    - safe-exceptions
    - semigroups
    - shakespeare
    - tagged
    - template-haskell
    - text
    - time
    - transformers
    - unordered-containers
    - uri-encode
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - websockets
    - yesod
    - yesod-auth
    - yesod-auth-oauth2 >= 0.6.1.5
    - yesod-core
    - yesod-form
    - yesod-paginator >= 1.1.0.2
    - yesod-persistent
    - yesod-static
    - yesod-websockets

executables:
  restyled.io:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - load-env
      - restyled

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - restyled
      - QuickCheck
      - bytestring
      - filepath
      - github
      - hedis
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - http-types
      - lens
      - load-env
      - megaparsec
      - monad-logger
      - persistent
      - rio
      - shakespeare
      - text
      - time
      - yesod-auth
      - yesod-core
      - yesod-test
