---
name: restyled
version: 0.1.1.0
license: MIT

# Dependencies shared in *all* targets
dependencies:
  - base

default-extensions:
  # TODO: move away from ClassyPrelude
  - NoImplicitPrelude

ghc-options: -Wall

library:
  dependencies:
    - aeson
    - aeson-casing
    - blaze-markup
    - bytestring
    - classy-prelude
    - classy-prelude-yesod
    - conduit
    - conduit-extra
    - containers
    - directory
    - envparse
    - errors
    - fast-logger
    - file-embed
    - filepath
    - formatting
    - github
    - gitrev
    - hedis
    - hjsmin
    - http-client
    - http-client-tls
    - http-conduit
    - http-types
    - hoauth2
    - jwt
    - load-env
    - megaparsec
    - monad-logger
    - mtl
    - persistent
    - persistent-postgresql
    - persistent-template
    - process
    - safe-exceptions
    - shakespeare
    - template-haskell
    - text
    - time
    - transformers
    - unix
    - unordered-containers
    - vector
    - wai
    - wai-extra
    - wai-logger
    - warp
    - yesod
    - yesod-auth
    - yesod-auth-oauth2
    - yesod-core
    - yesod-form
    - yesod-static
    - yesod-paginator >= 1.1.0.2
  source-dirs: src

executables:
  restyled.io:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - restyled

  restyled.io-backend:
    main: main.hs
    source-dirs: backend
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - restyled

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - restyled
      - HUnit
      - QuickCheck
      - bytestring
      - classy-prelude
      - hedis
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - megaparsec
      - monad-logger
      - persistent
      - resourcet
      - shakespeare
      - text
      - time
      - yesod-auth
      - yesod-core
      - yesod-test
