name: restyled
version: 0.1.1.0
license: MIT

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

  # Needed here just so HLint doesn't strip it
  - ViewPatterns

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - QuickCheck
    - aeson
    - aeson-casing
    - amazonka
    - amazonka-cloudwatch-logs
    - amazonka-core
    - blaze-html
    - blaze-markup
    - bytestring
    - cassava
    - composition-extra
    - conduit
    - conduit-extra
    - data-default
    - envparse
    - errors
    - esqueleto
    - extra
    - file-embed
    - formatting
    - generic-arbitrary
    - github
    - gitrev
    - graphula
    - hashable
    - hedis
    - hjsmin
    - hoauth2
    - http-conduit
    - http-types
    - iso8601-time
    - jwt
    - microlens
    - microlens-mtl
    - lens-aeson
    - load-env
    - megaparsec
    - monad-logger
    - monad-logger-aeson
    - monad-validate
    - mtl
    - optparse-applicative
    - path-pieces
    - persistent
    - persistent-postgresql
    - persistent-qq
    - postgresql-simple
    - quickcheck-instances
    - random
    - resourcet
    - retry
    - relude
    - safe-exceptions
    - semigroups
    - shakespeare
    - tagged
    - template-haskell
    - text
    - time
    - transformers
    - unliftio
    - unliftio-core
    - uri-encode
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - websockets
    - yesod
    - yesod-auth
    - yesod-auth-oauth2
    - yesod-core
    - yesod-form
    - yesod-page-cursor
    - yesod-persistent
    - yesod-static
    - yesod-websockets

    # Database.Redis.TLS
    - data-default-class
    - tls

executables:
  restyled.io:
    main: Main.hs
    source-dirs: web
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - restyled

  sync-marketplace:
    main: Main.hs
    source-dirs: sync-marketplace
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - restyled

  seed-db:
    main: Main.hs
    source-dirs: seed-db
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - restyled

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson-qq
      - restyled
      - QuickCheck
      - bytestring
      - filepath
      - github
      - graphula
      - hedis
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - hspec-expectations-json
      - http-types
      - microlens
      - lens-aeson
      - load-env
      - megaparsec
      - monad-validate
      - mtl
      - persistent
      - shakespeare
      - text
      - wai-extra
      - yesod-core
      - yesod-test
