resolver: lts-19.9
extra-deps:
  # The way it builds the newrelic shared library requires a local checkout for
  # some reason. Annoying
  - ../tracing-newrelic

  - github: brendanhay/amazonka
    commit: f73a957d05f64863e867cf39d0db260718f0fadd # main, as of SSO support
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-cloudwatch-logs
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts

  # https://github.com/hasura/monad-validate/pull/5
  - github: LeapYear/monad-validate
    commit: 5b181b7c57d6e2c975c533b0a0072e9aeb15fb99

  - monad-logger-aeson-0.2.0.0

  # For monad-logger-aeson
  - context-0.2.0.0
  # For weeder
  - algebraic-graphs-0.5

  # # For dbmigrations-postgresql
  - HDBC-postgresql-2.5.0.1
  - dbmigrations-2.0.0

  # For dbmigrations
  - yaml-light-0.1.4

  # For yaml-light
  - HsSyck-0.53
