#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOM'
Usage: plots/run [-s] <name>
Options:
  -s            Save temporarly plot image
  name          Name of plot to run, see plots/*
EOM
}

save=0

while getopts sh opt; do
  case "$opt" in
    s)
      save=1
      ;;
    h)
      usage
      exit
      ;;
    \?)
      usage >&2
      exit 64
      ;;
  esac
done

shift $((OPTIND - 1))

if (($# != 1)); then
  echo "NAME is required" >&2
  usage >&2
  exit 64
fi

name=$1
src=$(cd "$(dirname "$0")" && pwd)/$name

if [[ ! -d "$src" ]]; then
  echo "$src does not exist or is not a directory" >&2
  exit 1
fi

tmp=$(mktemp -d)

echo "Fetching data..."
heroku pg:psql --app restyled-io <"$src/query.sql" |
  tee "$tmp/data.csv" |
  head -n 10

echo "Plotting..."
gnuplot "$src/plot.gp" <"$tmp/data.csv" >"$tmp/output.png"

echo "Opening..."
$BROWSER "$tmp/output.png"

if ((save)); then
  cp -v "$tmp/output.png" "$HOME/restyled-plot-$name.$$.png"
fi
