#!/bin/bash
#
# This is a bit of a yak... Cloud Formation doesn't allow multi-line values in
# Stack parameters. Since we want to inject secrets via Stack parameters, they
# can't contain newlines. But GITHUB_APP_KEY needs newlines...
#
# This entrypoint solves this in a (slightly) generic way: it looks for
# environment variables that end in _BASE64, which are assumed to hold base64
# encoded (i.e. newline-free) content destined for the un-suffixed version of
# the same environment variable. The entrypoint decodes and sets these variables
# before proceeding with normal container startup, so the application code
# doesn't need to know about or support this translation.
#
###
tmp=$(mktemp)

env | sed '/\(.*\)_BASE64=\(.*\)/!d; s//\1 \2/g' | while read -r k v; do
  printf 'Exporting decoded %s from %s_BASE64...\n' "$k" "$k" >&2
  printf 'export %s="%s"\n' "$k" "$(base64 -d <<<"$v")" >>"$tmp"
done

# shellcheck disable=SC1090
source "$tmp"

if [ -n "$DOCKER_HOST" ]; then
  printf 'Configuring TLS for remote Docker host %s\n' "$DOCKER_HOST"
  export DOCKER_TLS_VERIFY="1"
  export DOCKER_CERT_PATH="$HOME/.docker/restyled/cert"
  mkdir -p "$DOCKER_CERT_PATH"

  set -u
  printf '%s\n' "$DOCKER_TLS_CACERT" >"$DOCKER_CERT_PATH"/ca.pem
  printf '%s\n' "$DOCKER_TLS_CERT" >"$DOCKER_CERT_PATH"/cert.pem
  printf '%s\n' "$DOCKER_TLS_KEY" >"$DOCKER_CERT_PATH"/key.pem
  set +u
fi

exec "$@"
