version: '3'

services:
  postgres:
    image: postgres:9.6.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restyled_test

  redis:
    image: redis:4.0.2-alpine
    ports:
      - 6379:6379

  build:
    image: fpco/stack-build:lts-13.3
    environment:
      GIT_AUTHOR_EMAIL: ci@restyled.io
      GIT_AUTHOR_NAME: Restyled.io CI
      GIT_COMMITTER_EMAIL: ci@restyled.io
      GIT_COMMITTER_NAME: Restyled.io CI
      STACK_ARGUMENTS: --no-terminal
    working_dir: ${BUILDKITE_BUILD_CHECKOUT_PATH}
    volumes:
      - '/cache/stack:/root/.stack'
      - '/cache/restyled.io/.stack-work:${BUILDKITE_BUILD_CHECKOUT_PATH}/.stack-work'

    depends_on:
      - postgres
      - redis

  ops:
    image: restyled/ops
    working_dir: ${BUILDKITE_BUILD_CHECKOUT_PATH}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
