#!/usr/bin/env bash
set -euo pipefail

psql_() {
  heroku pg:psql --app restyled-io
}

yes_to_proceed() {
  local ans

  echo
  read -r -p "To proceed, type YES: " ans
  [[ "$ans" == YES ]] || exit 0
}

from_jobs() {
  cat <<EOM
FROM job WHERE owner = '$1'
EOM
}

from_repos() {
  cat <<EOM
FROM repo WHERE owner = '$1'
EOM
}

from_users() {
  cat <<EOM
FROM "user" WHERE github_username = '$1'
EOM
}

from_accounts() {
  cat <<EOM
FROM marketplace_account
JOIN marketplace_plan
ON marketplace_plan.id = marketplace_account.marketplace_plan
WHERE marketplace_account.github_login = '$1'
EOM
}

from_accounts_delete() {
  cat <<EOM
FROM marketplace_account
WHERE marketplace_account.github_login = '$1'
EOM
}

review() {
  cat <<EOM
\set ON_ERROR_STOP on

SELECT
  'jobs' AS resource
  , count(*)
  , null AS details
$(from_jobs "$1")

UNION SELECT
  'repos' AS resource
  , count(*)
  , array_agg(name) AS details
$(from_repos "$1")

UNION SELECT
  'users' AS resource
  , count(*)
  , array_agg(email) AS details
$(from_users "$1")

UNION SELECT
  'accounts' AS resource
  , count(*)
  , array_agg(marketplace_plan.name) AS details
$(from_accounts "$1");
EOM
}

deletes() {
  cat <<EOM
DELETE $(from_jobs "$1");
DELETE $(from_repos "$1");
DELETE $(from_users "$1");
DELETE $(from_accounts_delete "$1");
EOM
}

github_username=$1

echo
echo ":: Querying all data for $github_username..."
review "$github_username" | psql_
yes_to_proceed

echo
echo ":: Performing dry-run deletion for $github_username..."
psql_ <<EOM
BEGIN;
$(deletes "$1")
ABORT;
EOM
yes_to_proceed

echo
echo ":: Performing ACTUAL deletion for $github_username..."
psql_ <<EOM
BEGIN;
$(deletes "$1")
COMMIT;
EOM
