#!/bin/sh
set -e

if [ -z "$1" ] || [ "$1" = upgrade ]; then
  for db in dev test; do
    echo "Upgrading $db database"
    "$0" "$db" upgrade
  done

  exit
fi

DBM_MIGRATION_STORE=$(cd "$(dirname "$0")" && pwd)/migrations

case "$1" in
  dev)
    DBM_DATABASE=postgres://postgres:password@localhost/restyled
    ;;
  test)
    DBM_DATABASE=postgres://postgres:password@localhost/restyled_test
    ;;
  prod)
    DBM_DATABASE=$(heroku config:get DATABASE_URL --app restyled-io)
    ;;
  *)
    echo "usage: migrate <env> <cmd>" >&2
    exit 64
    ;;
esac
shift

export DBM_DATABASE
export DBM_MIGRATION_STORE
exec stack exec -- moo-postgresql "$@"
