#!/bin/sh
set -e

DBM_DATABASE=$(heroku config:get DATABASE_URL --app restyled-io)

# Using an empty directory makes moo-upgrade *only* initialize the
# installed_migrations table for us.
DBM_MIGRATION_STORE=$(mktemp -d)

export DBM_DATABASE
export DBM_MIGRATION_STORE

echo "Initializing installed_migrations..."
stack exec -- moo-postgresql upgrade

for path in db/migrations/*.txt; do
  name=$(basename "$path" .txt)
  echo "Marking $name as migrated..."
  psql "$DBM_DATABASE" <<EOM
    INSERT INTO installed_migrations (migration_id)
    SELECT '$name' WHERE NOT EXISTS (
      SELECT migration_id FROM installed_migrations WHERE migration_id = '$name'
    );
EOM
done
