#!/bin/sh
set -e

# Local
# host=http://localhost:3000
# file=fixtures/webhooks/github/pull-request-opened.json

# Staging
host=https://staging.restyled.io
file=fixtures/webhooks/github/pull-request-opened-staging.json

curl \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d @"$file" "$host"/webhooks
