#!/bin/sh
if [ ! -f "$1" ]; then
  echo "usage: tools/webhook PAYLOAD_FILE [HOST]" >&2
  exit 1
fi

curl \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d @"$1" \
  "${2:-http://localhost:3000}"/webhooks
